### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'BERT_base' object has no attribute 'module'

### ISSUE THREAD

**Issue by gmseabra** [HyunSeobKim/MergedBERT#2]
Hi,

First of all, allow me to congratulate you for this very interesting work, and thank you for making the code available!!

Now, I went to try your code for fine-tuning the pre-trained model, and run into this error message. I believe I followed the directions correctly... 

I first got the code with 
```
$ git clone https://github.com/HyunSeobKim/CHEM-BERT
```
then I manually downloaded the `pretrained_model.pt` file and stored it in the `model` folder.

Inside the CHEM_BERT directory, I created a 'fine_tuning' folder with the following structure:
```
fine_tuning]$ tree
.
├── input
│   ├── dataset.csv
│   └── input.json
└── output
2 directories, 2 files
```
my `input.json` has the following:
```
fine_tuning]$ cat input/input.json 
{
"split_ratio":0.8,
"task":"regression",
"time":30
}
```

and the `dataset.csv`  file is a series of SMILES with Vina docking scores to a specific target:

```
fine_tuning]$ head input/dataset.csv 
O=C1c2c(C3=C1C1(C(=O)Nc4c1cccc4)C1=C(N3)c3c(C1=O)cccc3)cccc2,-10.0
O=c1oc2c(c3c1CCC3)c(OCC(=O)N1Cc3[nH]cnc3CC1)cc1c2CCC(O1)(C)C,-9.2
O=C(N/N=C/1\c2nc3c(nc2-c2c1cccc2)cccc3)c1c(O)cccc1,-9.1
O=c1oc2c(cc1c1nc(N3CCN(CC3)CC)[nH]c(=O)c1)cc1c(c2)N(C(C=C1C)(C)C)C,-9.1
S1(=O)(=O)N(c2c(-c3c1cccc3)cc(cc2)F)CC(=O)N1c2c(NC(=O)C1)cccc2,-9.0
O=C(N1Cc2c(nc(nc2CC1)C)N1CCCCC1)Nc1c2c(ccc1)cccc2,-9.0
O=C1N(c2nn3c(n2)NC(=CC3c2ccccc2)c2ccccc2)C(=O)C2C1CCCC2,-9.0
O=C(NC(C)C)c1c(NC(=O)C2c3c(Oc4c2cccc4)cccc3)cccc1,-9.0
O=C1N([C@@H]2N(c3c1cccc3)C(=O)c1c2cccc1)CCC(=O)Nc1cc2n(c(=O)n(c2cc1)C)C,-9.0
O=C1C2=C(OC(C1)C)c1c(NC2c2cc(O)ccc2)ccc2c1cccn2,-9.0
```

I then run the fine tuning service with the command below. It appeared to run fine for ~ 30 minutes, and then it crashed (apparently when trying to save the tuned model) with the message:
```
fine_tuning]$ python ../ft_service/finetuning_service.py
Traceback (most recent call last):
  File "../ft_service/finetuning_service.py", line 365, in <module>
    main()
  File "../ft_service/finetuning_service.py", line 259, in main
    torch.save(model.module.state_dict(), save_path)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'BERT_base' object has no attribute 'module'
```

Would you have any suggestions on what I may be doing wrong here?

Thanks,
Gustavo.

**Comment by HyunseobKim** [comment]
Use model.state_dict() instead of model.module.state_dict().

Thanks.

**Comment by gmseabra** [comment]
It works! Thanks!
